### ISSUE TITLE
希望打个包, 支持Linux

### ISSUE THREAD

**Issue by forifido** [solidSpoon/DashPlayer#41]
希望能打个包, 支持 Linux 桌面

**Comment by solidSpoon** [comment]
V3 及以前的版本都有 Linux 包, 但是我没测试过, 加上最近加了些调用本地能力的功能就暂时没打 Linux

**Comment by ovo-Tim** [comment]
我正在试着这样做 :hugs: 
https://github.com/ovo-Tim/DashPlayer-Linux

**Comment by solidSpoon** [comment]
> 我正在试着这样做 :hugs: 
> 
> https://github.com/ovo-Tim/DashPlayer-Linux

感谢🙏，我这确实没有Linux设备，没法做测试。

**Comment by ovo-Tim** [comment]
@solidSpoon 我修改了你的 github action 不过最后发布的时候一直报错
```
[FAILED] Resource not accessible by integration
[FAILED] Resource not accessible by integration
An unhandled rejection has occurred inside Forge:
HttpError: Resource not accessible by integration
at /home/runner/work/DashPlayer-Linux/DashPlayer-Linux/node_modules/@octokit/request/dist-src/fetch-wrapper.js:68:27
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Job.doExecute (/home/runner/work/DashPlayer-Linux/DashPlayer-Linux/node_modules/bottleneck/light.js:405:18)
```
改了权限也无济于事，你知道是怎么回事吗? :face_with_head_bandage: 
![image](https://github.com/solidSpoon/DashPlayer/assets/116942368/7fe65d84-87e7-46fb-8519-b9791921f623)

**Comment by solidSpoon** [comment]
![image](https://github.com/solidSpoon/DashPlayer/assets/39454841/ecbba716-afce-45cd-b9b2-bcb9714c4f62)

应该是这里没改吧，改成你自己的项目。

**Comment by ovo-Tim** [comment]
> @ovo-Tim 应该是这里没改吧，改成你自己的项目。

哦哦，感谢

**Comment by ovo-Tim** [comment]
![image](https://github.com/solidSpoon/DashPlayer/assets/116942368/972c3f1c-0caa-45ae-9b0a-ac6fd2259eef)
包打好啦，我测试一下就提个 PR 来 :cat:

**Comment by solidSpoon** [comment]
好！注意测试下视频切分那个功能，同时切分字幕和视频之后时间戳还能不能对上。

**Comment by ovo-Tim** [comment]
我这暂时拿不到 openai key 所以暂时测不了转录之类的功能啦

**Comment by solidSpoon** [comment]
好的

**Comment by solidSpoon** [comment]
在 v4.2.1 中新增了 Linux 打包

**Comment by garywill** [comment]
怎么只有rpm和deb啊，应该做个appimage

**Comment by ovo-Tim** [comment]
> 怎么只有rpm和deb啊，应该做个appimage

Electrion 默认只提供了这两种打包方式，appimage 需要使用额外的包

**Comment by ovo-Tim** [comment]
我仔细搜索了一下，项目现在用的打包方式是 Electron-Forge，很难打包成 AppImage。更好的打包方式应该是 electron-builder，不知道作者意向如何？

**Comment by ovo-Tim** [comment]
@solidSpoon 我正在尝试使用 electron-builder 打包，你知道这什么问题吗？（我不是专业的前端开发者）
![image](https://github.com/solidSpoon/DashPlayer/assets/116942368/14d160d3-2c16-460b-9b04-1c59776ddb32)

**Comment by solidSpoon** [comment]
😂我也是边写边学的。改成electron builder 的话后续forge做版本升级会麻烦吗？我这可能要过几周才方便维护这个项目

**Comment by ovo-Tim** [comment]
@solidSpoon 用了electron builder 不就可以弃用 forge 了嘛

害，这个东西把我整麻了 😂，不应该这样编译吗？
![image](https://github.com/solidSpoon/DashPlayer/assets/116942368/9aa0cdef-387f-4a56-8de5-9416a17bda6e)

**Comment by solidSpoon** [comment]
这个项目最开始是用这个模板写的

https://github.com/electron-react-boilerplate/electron-react-boilerplate

这个模板好像是用的electron builder打包，后来我嫌弃它代码太老了就迁移到electron
forge了。

目前DashPlayer整个都是用electron forge模板写的，我猜测应该不好换，我也不太懂😂。

**Comment by solidSpoon** [comment]
李笑来老师的 enjoy 项目也是 Electron Forge 写的，我看 enjoy 也没提供 Appimage 打包

https://github.com/xiaolai/everyone-can-use-english

**Comment by ovo-Tim** [comment]
@solidSpoon 就是说 forge 不好打包成别的格式，所以要换成 buider 呐🥵
